#!/usr/bin/env python3
"""Update data/contracts.json + generate apps/frontend/.env.mainnet.example after deploy.
Never invents addresses. Never writes PEM.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "data" / "contracts.json"
VITE_OUT = ROOT / "apps" / "frontend" / ".env.mainnet.example"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--agents", default=None, help="agents_marketplace erd1...")
    p.add_argument("--marketplace", default=None, help="nft marketplace erd1...")
    args = p.parse_args()
    data: dict = {}
    if PATH.exists():
        data = json.loads(PATH.read_text(encoding="utf-8"))
    data.setdefault("network", "mainnet")
    data.setdefault("chainId", "1")
    data["updated"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    contracts = data.setdefault("contracts", {})
    if args.agents:
        if not args.agents.startswith("erd1"):
            raise SystemExit("agents address must be erd1...")
        contracts["agents_marketplace"] = args.agents
    if args.marketplace:
        if not args.marketplace.startswith("erd1"):
            raise SystemExit("marketplace address must be erd1...")
        contracts["marketplace"] = args.marketplace
    data["contracts"] = contracts

    mkt = contracts.get("marketplace")
    ag = contracts.get("agents_marketplace")
    data["verification"] = {
        "marketplace_mainnet": {
            "address": mkt,
            "note": "Run: python scripts/verify_marketplace_codehash.py — codeHash must be non-null",
        },
        "agents_marketplace": ag or "null — deploy required",
    }
    data["gaps"] = {
        "agents_marketplace": None if ag else "P0 deploy agents-marketplace",
        "marketplace": None if mkt else "P0 deploy nft-marketplace",
        "marketplace_placeBid": "Confirm codehash includes placeBid after deploy",
        "LIA_LIVE_TRADING": "Keep 0 until micro-trades OK",
    }
    PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
    print("wrote", PATH)

    # VITE template for Pages rebuild (no secrets)
    lines = [
        "# Generated by post_deploy_contracts.py — copy values into CI / local .env",
        "# Do not commit real .env with secrets",
        "VITE_CHAIN_ID=1",
        f"VITE_MARKETPLACE_ADDRESS={mkt or ''}",
        f"VITE_AGENTS_MARKETPLACE_ADDRESS={ag or ''}",
        "VITE_AGENTS_FEE_BPS=300",
        "VITE_LIA_PROTOCOL_WALLET=erd1p4zyy5476u5nkw4hprhk6dh63znvksm4ppkxglxqasz2kum0lerqu0crn6",
        "",
    ]
    VITE_OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", VITE_OUT)
    print(json.dumps(contracts, indent=2))
    print("Next: python scripts/verify_marketplace_codehash.py && rebuild GH Pages")


if __name__ == "__main__":
    main()
